/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hravjave;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JFrame;

/**
 *
 * @author DanoCZE
 */
public class MainWindow extends javax.swing.JFrame {

    private Playground playground;
    private Color z;
    private Color m;
    private Color zz;
    private Color zm;
    private Boolean drawing;
    
    public MainWindow() {
        this.z = Color.BLACK;
        this.m = Color.WHITE;
        this.zz = Color.DARK_GRAY;
        this.zm = Color.LIGHT_GRAY;
        this.drawing = false;
        this.setPreferredSize(new Dimension(1280, 720));
        playground = new Playground(this,z,m,zz,zm);
        this.add(playground);
        
        initComponents();
        bZive.setBackground(z);
        bMrtve.setBackground(m);
        bZmena_zive.setBackground(zz);
        bZmena_mrtve.setBackground(zm);
    }
    
    public void setText(int pocet, int aktivnich, Boolean presFail) {
        infoBar.setText("Žijících buněk: " + Integer.toString(pocet) + " | "
                + "Proběhlo: " + Integer.toString(aktivnich) 
                + " změn | Šířka buňky: " + Integer.toString(playground.getW()) 
                + " | Rychlost vývoje: " + Integer.toString(rychlost.getValue()) 
                + "ms"+((presFail)? " | FAIL ":" ")
                +"");
    }
    
    public void setVel(Boolean v) {
        vel.setSelected(v);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        infoBar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        newPreset = new javax.swing.JButton();
        rychlost = new javax.swing.JSlider();
        sirka_label = new javax.swing.JLabel();
        newRandom = new javax.swing.JButton();
        sirka = new javax.swing.JSlider();
        rychlost_label = new javax.swing.JLabel();
        rychlost_text = new javax.swing.JLabel();
        bZive = new javax.swing.JPanel();
        bMrtve = new javax.swing.JPanel();
        bZmena_zive = new javax.swing.JPanel();
        bZmena_mrtve = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        presety = new javax.swing.JComboBox<>();
        newCustom = new javax.swing.JButton();
        save = new javax.swing.JButton();
        nacist = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        vel = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hra života");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 670));
        setPreferredSize(new java.awt.Dimension(800, 670));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 670));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 20));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 20));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 20));

        infoBar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        infoBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoBar.setText("STATUS BAR :)");
        infoBar.setMaximumSize(new java.awt.Dimension(600, 20));
        infoBar.setMinimumSize(new java.awt.Dimension(600, 20));
        infoBar.setPreferredSize(new java.awt.Dimension(600, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(infoBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(200, 32000));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 600));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 600));

        newPreset.setText("Nastavit");
        newPreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPresetActionPerformed(evt);
            }
        });

        rychlost.setFont(new java.awt.Font("Arial Unicode MS", 0, 5)); // NOI18N
        rychlost.setMajorTickSpacing(100);
        rychlost.setMaximum(1900);
        rychlost.setMinimum(100);
        rychlost.setMinorTickSpacing(1500);
        rychlost.setToolTipText("Šířka pole");
        rychlost.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rychlostStateChanged(evt);
            }
        });

        sirka_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sirka_label.setLabelFor(rychlost);
        sirka_label.setText("Šířka pole");
        sirka_label.setToolTipText("");

        newRandom.setText("Nové náhodné");
        newRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRandomActionPerformed(evt);
            }
        });

        sirka.setFont(new java.awt.Font("Arial Unicode MS", 0, 10)); // NOI18N
        sirka.setMajorTickSpacing(5);
        sirka.setMaximum(35);
        sirka.setMinimum(5);
        sirka.setMinorTickSpacing(5);
        sirka.setPaintLabels(true);
        sirka.setPaintTicks(true);
        sirka.setToolTipText("Šířka pole");
        sirka.setValue(10);
        sirka.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sirkaStateChanged(evt);
            }
        });

        rychlost_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rychlost_label.setLabelFor(rychlost);
        rychlost_label.setText("Rychlost generace (ms)");
        rychlost_label.setToolTipText("");

        rychlost_text.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        rychlost_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rychlost_text.setText("100ms");

        bZive.setBackground(new java.awt.Color(0, 255, 255));
        bZive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bZive.setPreferredSize(new java.awt.Dimension(30, 30));
        bZive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bZiveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bZiveLayout = new javax.swing.GroupLayout(bZive);
        bZive.setLayout(bZiveLayout);
        bZiveLayout.setHorizontalGroup(
            bZiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bZiveLayout.setVerticalGroup(
            bZiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        bMrtve.setBackground(new java.awt.Color(0, 255, 255));
        bMrtve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bMrtve.setPreferredSize(new java.awt.Dimension(30, 30));
        bMrtve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMrtveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bMrtveLayout = new javax.swing.GroupLayout(bMrtve);
        bMrtve.setLayout(bMrtveLayout);
        bMrtveLayout.setHorizontalGroup(
            bMrtveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bMrtveLayout.setVerticalGroup(
            bMrtveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        bZmena_zive.setBackground(new java.awt.Color(0, 255, 255));
        bZmena_zive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bZmena_zive.setPreferredSize(new java.awt.Dimension(30, 30));
        bZmena_zive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bZmena_ziveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bZmena_ziveLayout = new javax.swing.GroupLayout(bZmena_zive);
        bZmena_zive.setLayout(bZmena_ziveLayout);
        bZmena_ziveLayout.setHorizontalGroup(
            bZmena_ziveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bZmena_ziveLayout.setVerticalGroup(
            bZmena_ziveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        bZmena_mrtve.setBackground(new java.awt.Color(0, 255, 255));
        bZmena_mrtve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bZmena_mrtve.setPreferredSize(new java.awt.Dimension(30, 30));
        bZmena_mrtve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bZmena_mrtveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bZmena_mrtveLayout = new javax.swing.GroupLayout(bZmena_mrtve);
        bZmena_mrtve.setLayout(bZmena_mrtveLayout);
        bZmena_mrtveLayout.setHorizontalGroup(
            bZmena_mrtveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bZmena_mrtveLayout.setVerticalGroup(
            bZmena_mrtveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Živá");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mrtvá");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Změna na živou");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Změna na mrtvou");

        presety.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blikač (osc)", "Ropucha (osc)", "Maják (osc)", "Pulzar (osc)", "Dělo", "Křídlo", "Lehká hvězdná loď" }));
        presety.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presetyActionPerformed(evt);
            }
        });

        newCustom.setText("Nové vlastní");
        newCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomActionPerformed(evt);
            }
        });

        save.setText("Uložit");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        nacist.setText("Načíst");
        nacist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacistActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 153, 153));
        clear.setText("Vyčistit");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        vel.setText("3x3");
        vel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rychlost, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sirka_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newRandom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rychlost_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sirka, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(rychlost_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(bZive, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(bZmena_zive, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bZmena_mrtve, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(bMrtve, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(presety, 0, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newPreset))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(newCustom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nacist, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sirka_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sirka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rychlost_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rychlost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rychlost_text)
                .addGap(21, 21, 21)
                .addComponent(newRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vel))
                    .addComponent(newCustom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bMrtve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bZive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bZmena_mrtve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bZmena_zive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presety, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPreset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(nacist)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 200, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPresetActionPerformed
        playground.setPresetEn(!playground.getPresetEn());
        if (playground.getPresetEn()) {
            newPreset.setBackground(Color.DARK_GRAY);
            newPreset.setOpaque(true);
            playground.setPres(presety.getSelectedIndex());
        } else {
            newPreset.setBackground(Color.LIGHT_GRAY);
            newPreset.setOpaque(true);
        }
                
            
    }//GEN-LAST:event_newPresetActionPerformed

    private void newRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRandomActionPerformed
        playground.generate();
        //playground.startStop();
    }//GEN-LAST:event_newRandomActionPerformed

    private void rychlostStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rychlostStateChanged
        playground.setS(rychlost.getValue());
        rychlost_text.setText(Integer.toString(rychlost.getValue()) + "ms");
    }//GEN-LAST:event_rychlostStateChanged

    private void sirkaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sirkaStateChanged
        playground.setW(sirka.getValue());
    }//GEN-LAST:event_sirkaStateChanged

    private void bZiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bZiveMouseClicked
        JFrame ColorPicker = new JFrame("Výběr barvy");
        Color barva = JColorChooser.showDialog(ColorPicker,"Vyber barvu živých buněk",bZive.getBackground());
        if (barva != null) {
            playground.setZ(barva);
            bZive.setBackground(barva);
        }
    }//GEN-LAST:event_bZiveMouseClicked

    private void bMrtveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMrtveMouseClicked
        JFrame ColorPicker = new JFrame("Výběr barvy");
        Color barva = JColorChooser.showDialog(ColorPicker,"Vyber barvu mrtvých buněk",bMrtve.getBackground());
        if (barva != null) {
            playground.setM(barva);
            bMrtve.setBackground(barva);
        }
    }//GEN-LAST:event_bMrtveMouseClicked

    private void bZmena_ziveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bZmena_ziveMouseClicked
        JFrame ColorPicker = new JFrame("Výběr barvy");
        Color barva = JColorChooser.showDialog(ColorPicker,"Vyber barvu pro změnu buňky na živou",bZmena_zive.getBackground());
        if (barva != null) {
            playground.setZZ(barva);
            bZmena_zive.setBackground(barva);
        }
    }//GEN-LAST:event_bZmena_ziveMouseClicked

    private void bZmena_mrtveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bZmena_mrtveMouseClicked
        JFrame ColorPicker = new JFrame("Výběr barvy");
        Color barva = JColorChooser.showDialog(ColorPicker,"Vyber barvu pro změnu buňky na mrtvou",bZmena_mrtve.getBackground());
        if (barva != null) {
            playground.setZM(barva);
            bZmena_mrtve.setBackground(barva);
        }
    }//GEN-LAST:event_bZmena_mrtveMouseClicked

    private void presetyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presetyActionPerformed
        playground.setPres(presety.getSelectedIndex());
    }//GEN-LAST:event_presetyActionPerformed

    private void newCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomActionPerformed
        if(this.drawing) {
            this.drawing = false;
            playground.setDrawing(false);
            newCustom.setBackground(Color.LIGHT_GRAY);
            newCustom.setOpaque(false);
            playground.timer.start();
        } else {
            this.drawing = true;
            playground.setDrawing(true);
            newCustom.setBackground(Color.DARK_GRAY);
            newCustom.setOpaque(true);
            playground.timer.stop();
        }
    }//GEN-LAST:event_newCustomActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        playground.ulozit();
    }//GEN-LAST:event_saveActionPerformed

    private void nacistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacistActionPerformed
        playground.nacist();
    }//GEN-LAST:event_nacistActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        playground.clear();
    }//GEN-LAST:event_clearActionPerformed

    private void velActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velActionPerformed
        playground.setVelikost(vel.isSelected());
    }//GEN-LAST:event_velActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bMrtve;
    private javax.swing.JPanel bZive;
    private javax.swing.JPanel bZmena_mrtve;
    private javax.swing.JPanel bZmena_zive;
    private javax.swing.JButton clear;
    private javax.swing.JLabel infoBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nacist;
    private javax.swing.JButton newCustom;
    private javax.swing.JButton newPreset;
    private javax.swing.JButton newRandom;
    private javax.swing.JComboBox<String> presety;
    private javax.swing.JSlider rychlost;
    private javax.swing.JLabel rychlost_label;
    private javax.swing.JLabel rychlost_text;
    private javax.swing.JButton save;
    private javax.swing.JSlider sirka;
    private javax.swing.JLabel sirka_label;
    private javax.swing.JCheckBox vel;
    // End of variables declaration//GEN-END:variables
}


